name: Java 1.8 Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Java 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.7
      
      - name: Build with Maven
        run: mvn package
