# GitHub Actions YAML

name: GitHub Actions Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: 'microsoft'
      
      - name: Build with Maven
        run: mvn package --file pom.xml
      
      - name: Copy files
        run: cp -R target $(Build.ArtifactStagingDirectory)
      
      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: $(Build.ArtifactStagingDirectory)
